# -*- coding: utf-8 -*-
"""Simulation labs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vF1Z29ElMGYl_nRH-82wihajD9W6Cv_A
"""

import matplotlib.pyplot as plt
import numpy as np

n = 100
dt= 1/n

C1 = [0]
C2 = [2]
C3 = [10]

i = 0

K1 = 10
K2 = 1
for i in range(1,n):
    dC = (K2*C3[i-1]-K1*C1[i-1]*C2[i-1])*dt;
    C1.append(C1[i-1]+ dC)
    C2.append(C2[i-1]+ dC)
    C3.append(C3[i-1]- 2* dC)

print(C1)

fig = plt.figure()
plt.plot(C1, label = "C1")
plt.plot(C2, label = "C2")
plt.plot(C3, label = "C3")

plt.legend()
plt.show()