# -*- coding: utf-8 -*-
"""Simulation labs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vF1Z29ElMGYl_nRH-82wihajD9W6Cv_A
"""

import matplotlib.pyplot as plt
import numpy as np

# Constants
h = 0.0002
a11 = -50
a21 = -10000
a22 = -21.5
n = 500

# Variables
ein = 0
V1 =[10]
V2 = [100]

def function1(v1):
  return a11*v1-a11*ein;
def function2(v1,v2):
  return a21*v1+a22*v2-a21*ein;

for i in range(0,n-1):
  m11 = function1(V1[i])
  m12 = function1(V1[i] + m11 * h/2)
  m13 = function1(V1[i] + m12 * h/2)
  m14 = function1(V1[i]+ m13 * h)
  V1.append(V1[i]+ (m11 + 2 * m12 + 2 * m13 + m14)/6 * h)

  m21 = function2(V1[i],V2[i])
  m22 = function2(V1[i] +  h/2, V2[i] + m21 * h/2)
  m23 = function2(V1[i] +  h/2 , V2[i] + m22 * h/2)
  m24 = function2(V1[i]+  h, V2[i]+ m23 * h)
  V2.append(V2[i]+ (m21 + 2*m22 + 2*m23 + m24)/6 * h)

fig = plt.figure()
plt.xlim([0,n-1])
plt.plot(V1,label = "V1")
plt.legend()
plt.show()
plt.xlim([0,n-1])
plt.plot(V2,label ="V2")
plt.legend()
plt.show()