# -*- coding: utf-8 -*-
"""Simulation labs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vF1Z29ElMGYl_nRH-82wihajD9W6Cv_A
"""

import matplotlib.pyplot as plt
from scipy import signal

#constants
k = 10
m = 20
D = [4, 8, 16, 20, 40, 80]

for i in range(0,5):
    A = [[0, 1], [-k/m, -D[i]/m]]
    B = [[0], [k/m]]
    C = [1, 0]
    E = [0]
    my_ss = signal.StateSpace(A, B, C, E)
    plt.xlabel('Time')
    plt.ylabel('Position of mass')
    t, y = signal.step(my_ss)
    plt.plot(t, y)

plt.legend(['0.2', '0.4', '0.8', '1', '2', '4'])