# -*- coding: utf-8 -*-
"""Simulation labs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vF1Z29ElMGYl_nRH-82wihajD9W6Cv_A
"""

import matplotlib.pyplot as plt

G=[35000];
N = 50
for i in range (1,N-1):
    G.append(((G[i-1]*2+1000) % 10000)+30000)

Y = [40000]
I = [0]
T = [0]
C =[0]

for j in range(1,N-1):
    I.append(2+0.1*Y[j-1])
    Y.append(45.45+2.27*(I[j]+G[j]))
    T.append(0.2*Y[j])
    C.append(20+0.7*(Y[j]-T[j]))

fig = plt.figure()
plt.plot(Y,label="National Income(Y)")
plt.plot(C,label="Consumption(C)")
plt.plot(I,label="Investment(I)")
plt.plot(T,label="Taxes(T)")
plt.plot(G,label="Expenditure(G)")
plt.legend()
plt.show()